### ISSUE TITLE
Caitiff clan is broken

### ISSUE THREAD

**Issue by RobinZergiebel** [oraum/VTMsite#13]
When users choose the Caitiff clan for their character, they should have to pick 3 disciplines for their "clan disciplines".

**Comment by oraum** [comment]
I see there is no add discipline button even on freebie mode so there ist no way to add any discipline. 
But I do no get what the expected behavior would be, based on the current description. 
Do we need three empty discipline fields if the users chooses Caitiff, a simple add disciplines button (maybe on freebie), a popup asking the user to select the disciplines right ahead or something completely different?
